name: Simulate Merge Queue

on:
  merge_group:

jobs:
  simulate-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Random Delay
        id: delay
        run: |
          # Generate a random delay between 60 seconds (1 min) and 121 seconds (2 min)
          DELAY=$((60 + RANDOM % 61))
          echo "Waiting for $DELAY seconds..."
          echo "delay=$DELAY" >> $GITHUB_ENV

      - name: Wait Random Time
        run: sleep ${{ env.delay }}

      - name: Simulate 30% Failure
        id: simulate-failure
        run: |
          # Generate a random number between 0 and 99
          RANDOM_NUM=$((RANDOM % 100))
          echo "Generated random number: $RANDOM_NUM"
          
          # Fail the job if the random number is less than 50 (50% chance)
          if [ $RANDOM_NUM -lt 50 ]; then
            echo "Simulating a failure... (50% chance hit)"
            exit 1
          fi
          echo "Simulation passed!"

      - name: Report Success
        if: success()
        run: echo "Workflow completed successfully 🎉"

      - name: Report Failure
        if: failure()
        run: echo "Workflow failed due to simulated failure. 💥"
